---
# 5. Case Study: Analisis Data FMCG

## 🎯 Objective
Kita akan menganalisis dataset penjualan FMCG nyata dari perusahaan yang menjual produk kebutuhan sehari-hari melalui berbagai channel (Offline, Online Toko Oren, Online Toko Hijau).

Dataset ini **messy**, mengandung berbagai masalah data yang harus dibersihkan sebelum dianalisis.

### Business Questions:
1. Berapa total revenue dan komposisi per kategori produk?
2. Channel penjualan mana yang paling menguntungkan?
3. Bagaimana tren penjualan per bulan?
4. Produk apa yang paling laris?
5. Kota mana dengan penjualan tertinggi?
6. Bagaimana distribusi status order dan rating pelanggan?
7. Top 10 Pelanggan Paling Aktif
8. Kategori Terlaris pada Setiap Channel

### Import Datasets and Import Library

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

# Load dataset
# Jika di Google Colab: upload file atau mount Google Drive terlebih dahulu
df_raw = pd.read_csv("Data FMCG_BT Data Analyst - Messy.csv", sep=';')
print(f'Shape awal : {df_raw.shape}')
print(f'Kolom      : {df_raw.columns.tolist()}')
print()
df_raw.head(10)

Shape awal : (20007, 16)
Kolom      : ['sales_date', 'order_id', 'product_name', 'category', 'price', 'quantity', 'total', 'discount', 'shipping_fee', 'total_sales', 'customer_name', 'customer_address', 'channel', 'rating', 'status', 'Unnamed: 15']

,sales_date,order_id,product_name,category,price,quantity,total,discount,shipping_fee,total_sales,customer_name,customer_address,channel,rating,status,Unnamed: 15
0,01/01/2025,P00001,Minyak Goreng,Makanan,18000.0,1.0,NaN,0.15,20000.0,NaN,Shinta,Malang,Toko_Oren_Online,5.0,Returned,NaN
1,01/01/2025,P00002,Kopi,Makanan,25000.0,3.0,NaN,0.15,22000.0,NaN,Eli,Makassar,Offline,4.0,Failed,NaN
2,01/01/2025,P00003,Deterjen,PEMBERSIH,10000.0,3.0,NaN,0.15,25000.0,NaN,Eka,Medan,Offline,1.0,Pending,NaN
3,01/01/2025,P00004,Minyak Goreng,makanan,18000.0,1.0,NaN,0.15,20000.0,NaN,Zenia,Surabaya,Online - Toko Oren,3.0,Pending,NaN
4,01/01/2025,P00005,Pasta Gigi,Perawatan,15000.0,3.0,NaN,0.15,12000.0,NaN,Dicky,Bogor,Online - Toko Oren,1.0,Returned,NaN
5,01/01/2025,P00006,Minyak Goreng,makanan,18000.0,3.0,NaN,0.15,22000.0,NaN,Santi,Makassar,Online - Toko Oren,1.0,Pending,NaN
6,01/01/2025,P00007,Sabun Mandi,PEMBERSIH,7000.0,3.0,NaN,0.15,25000.0,NaN,Farhan,Medan,Offline,5.0,Failed,NaN
7,01/01/2025,P00008,Pembersih Lantai,pembersih,8000.0,1.0,NaN,0.15,22000.0,NaN,Dewa,Makassar,Online - Toko Oren,1.0,Sukses,NaN
8,01/01/2025,P00009,Pasta Gigi,PERAWATAN,15000.0,3.0,NaN,0.15,30000.0,NaN,Zara,Samarinda,Offline,5.0,Pending,NaN
9,01/01/2025,P00010,Shampo,PERAWATAN,20000.0,2.0,NaN,0.15,18000.0,NaN,Putra,Yogyakarta,Online - Toko Hijau,5.0,Failed,NaN

In [3]:
df_raw.describe()

,price,quantity,total,discount,shipping_fee,total_sales,rating,Unnamed: 15
count,20006.000000,20006.000000,0.0,20006.000000,20006.000000,0.0,20006.00000,0.0
mean,13506.398081,1.971659,NaN,0.009627,17061.881436,NaN,2.99900,NaN
std,6004.658198,1.793416,NaN,0.036762,7081.753436,NaN,1.41873,NaN
min,5000.000000,-99.000000,NaN,0.000000,0.000000,NaN,1.00000,NaN
25%,8000.000000,1.000000,NaN,0.000000,12000.000000,NaN,2.00000,NaN
50%,15000.000000,2.000000,NaN,0.000000,18000.000000,NaN,3.00000,NaN
75%,18000.000000,3.000000,NaN,0.000000,22000.000000,NaN,4.00000,NaN
max,25000.000000,3.000000,NaN,0.150000,30000.000000,NaN,5.00000,NaN

### Step 2: Identifikasi Masalah Data

In [4]:
df_raw[df_raw['quantity'] <= 0]

,sales_date,order_id,product_name,category,price,quantity,total,discount,shipping_fee,total_sales,customer_name,customer_address,channel,rating,status,Unnamed: 15
14,01/01/2025,P00015,Kopi,Makanan,25000.0,-99.0,NaN,0.15,25000.0,NaN,Mutiara,Medan,Offline,1.0,Sukses,NaN
134,03/01/2025,P00133,Pembersih Wajah,Perawatan,12000.0,-99.0,NaN,0.00,15000.0,NaN,Vera,Jakarta,Online - Toko Hijau,5.0,Failed,NaN
174,04/01/2025,P00173,Pembersih Wajah,PERAWATAN,12000.0,-99.0,NaN,0.00,20000.0,NaN,Irma,Malang,hijau_toko_web,3.0,Returned,NaN
235,05/01/2025,P00233,Shampo,PERAWATAN,20000.0,-99.0,NaN,0.00,20000.0,NaN,Gilang,Malang,Offline,5.0,Sukses,NaN
285,06/01/2025,P00283,Minyak Goreng,Makanan,18000.0,-99.0,NaN,0.00,20000.0,NaN,Cindy,Malang,Online - Toko Hijau,2.0,Failed,NaN

In [5]:
print('=== 1. MISSING VALUES ===')
missing = df_raw.isnull().sum()
persen = (missing / len(df_raw) * 100).round(2)
print(pd.DataFrame({'Jumlah Missing': missing, 'Persentase Missing (%)': persen}))


print('=== 2. DUPLICATE VALUES ===')
print(f"Jumlah baris duplicate : {df_raw.duplicated().sum()}")

print(f'\n===3. NILAI UNTUK KOLOM KATEGORIKAL ===')
for col in ['category', 'channel', 'status']:
    print(f"{col} : {df_raw[col].unique()}")

print(f"\n=== 4. QUANTITY TIDAK VALID ===")
print(df_raw[df_raw['quantity'] <= 0][['order_id', 'product_name', 'quantity']])

print(f"\n=== 5. PRODUCT NAME DENGAN SPASI ===")
spasi = df_raw[df_raw['product_name'].str.startswith('', na=False)]['product_name'].unique()
print(spasi)

=== 1. MISSING VALUES ===
                  Jumlah Missing  Persentase Missing (%)
sales_date                     1                     0.0
order_id                       1                     0.0
product_name                   1                     0.0
category                       1                     0.0
price                          1                     0.0
quantity                       1                     0.0
total                      20007                   100.0
discount                       1                     0.0
shipping_fee                   1                     0.0
total_sales                20007                   100.0
customer_name                  1                     0.0
customer_address               1                     0.0
channel                        1                     0.0
rating                         1                     0.0
status                         1                     0.0
Unnamed: 15                20007                   100.0
=== 2. DUPLICATE VALUES ===
Jumlah baris duplicate : 6

===3. NILAI UNTUK KOLOM KATEGORIKAL ===
category : ['Makanan' 'PEMBERSIH' 'makanan' 'Perawatan' 'pembersih' 'PERAWATAN'
 'Pembersih' 'MAKANAN' 'perawatan' nan]
channel : ['Toko_Oren_Online' 'Offline' 'Online - Toko Oren' 'Online - Toko Hijau'
 'hijau_toko_web' nan]
status : ['Returned' 'Failed' 'Pending' 'Sukses' nan]

=== 4. QUANTITY TIDAK VALID ===
    order_id        product_name  quantity
14    P00015                Kopi     -99.0
134   P00133     Pembersih Wajah     -99.0
174   P00173    Pembersih Wajah      -99.0
235   P00233              Shampo     -99.0
285   P00283       Minyak Goreng     -99.0

=== 5. PRODUCT NAME DENGAN SPASI ===
['Minyak Goreng' 'Kopi' '  Deterjen ' '  Minyak Goreng ' '  Pasta Gigi '
 '  Sabun Mandi ' 'Pembersih Lantai' 'Pasta Gigi' 'Shampo' 'Deterjen'
 'Pembersih Wajah' 'Sabun Mandi' '  Teh ' 'Sabun Cuci' 'Teh'
 '  Pembersih Lantai ' '  Sabun Cuci ' '  Shampo ' '  Kopi '
 '  Pembersih Wajah ']

### Step 3: Data Cleansing


| # | Masalah | Solusi |
|---|---------|--------|
| 1 | Kolom `total`, `total_sales`, `Unnamed: 15` semua kosong | Drop kolom |
| 2 | 1 baris missing values | Drop baris |
| 3 | 6 baris duplikat | Drop duplicates |
| 4 | Quantity bernilai -99 | Drop baris tidak valid |
| 5 | Spasi di `product_name` | Strip + title case |
| 6 | `category` tidak konsisten | Standarisasi title case |
| 7 | `channel` tidak konsisten | Mapping ke nama standar |
| 8 | `total` & `total_sales` kosong | Hitung ulang dari kolom lain |

In [6]:
df = df_raw.copy()

# 1. Hapus  Kolom Tidak Relevan
df = df.drop(columns=['total', 'total_sales', 'Unnamed: 15'])
print(f"Setelah drop columns : {df.shape}")

# 2. Hapus baris dengan missing values
df = df.dropna(how='any').reset_index(drop=True)
print(f"Setelah dropna : {df.shape}")

# 3. Hapus duplikat
df = df.drop_duplicates(keep='first').reset_index(drop=True)
print(f"Setelah hapus duplikat : {df.shape}")

# 4. Hapus baris dengan quantity <= 0
df = df[df['quantity'] > 0].reset_index(drop=True)
print(f"Setelah hapus quantity tidak valid : {df.shape}")

Setelah drop columns : (20007, 13)
Setelah dropna : (20006, 13)
Setelah hapus duplikat : (20000, 13)
Setelah hapus quantity tidak valid : (19995, 13)

In [7]:
# --- 5. Bersihkan product_name ---
df['product_name'] = df['product_name'].str.strip().str.title()

# --- 6. Standarisasi category ---
df['category'] = df['category'].str.strip().str.title()

# --- 7. Standarisasi channel ---
channel_map = {
    'Toko_Oren_Online'   : 'Online - Toko Oren',
    'hijau_toko_web'     : 'Online - Toko Hijau',
    'Offline'            : 'Offline',
    'Online - Toko Oren' : 'Online - Toko Oren',
    'Online - Toko Hijau': 'Online - Toko Hijau'
}
df['channel'] = df['channel'].map(channel_map)

# --- Standarisasi teks lainnya ---
df['customer_name']    = df['customer_name'].str.strip().str.title()
df['customer_address'] = df['customer_address'].str.strip().str.title()

print('Nilai unik category setelah cleaning:', df['category'].unique())
print('Nilai unik channel  setelah cleaning:', df['channel'].unique())

Nilai unik category setelah cleaning: ['Makanan' 'Pembersih' 'Perawatan']
Nilai unik channel  setelah cleaning: ['Online - Toko Oren' 'Offline' 'Online - Toko Hijau']

### Step 4 : Data Formatting

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19995 entries, 0 to 19994
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sales_date        19995 non-null  object
 1   order_id          19995 non-null  object
 2   product_name      19995 non-null  object
 3   category          19995 non-null  object
 4   price             19995 non-null  float64
 5   quantity          19995 non-null  float64
 6   discount          19995 non-null  float64
 7   shipping_fee      19995 non-null  float64
 8   customer_name     19995 non-null  object
 9   customer_address  19995 non-null  object
 10  channel           19995 non-null  object
 11  rating            19995 non-null  float64
 12  status            19995 non-null  object
dtypes: float64(5), object(8)
memory usage: 2.0+ MB

In [9]:
df = df[df['sales_date'] != '12/31/2025']

In [10]:
# Format Tanggal
df['sales_date'] = pd.to_datetime(df['sales_date'], format='%d/%m/%Y')

# Ekstrak komponen tanggal
df['month'] = df['sales_date'].dt.month
df['month_name'] = df['sales_date'].dt.strftime('%B')
df['quarter'] = df['sales_date'].dt.quarter


# Perbaiki tipe data pada kolom numerik
df['price'] = df['price'].astype(float)
df['quantity'] = df['quantity'].astype(int)
df['discount'] = df['discount'].astype(float)
df['shipping_fee'] = df['shipping_fee'].astype(float)
df['rating'] = df['rating'].astype(int)


# Hitung Kolom Total dan Total Sales
df['total'] = df['price'] * df['quantity']
df['total_sales'] = df['total'] - (1 - df['discount']) + df['shipping_fee']

# Kolom Kategori Rating
df['rating_category'] = df['rating'].apply(
    lambda r: 'Positif' if r >= 4 else ('Netral' if r == 3 else 'Negatif')
)

print("=== PERBANDINGAN SEBELUM VS SESUDAH CLEANING ===")
print(f"Shape Awal : {df_raw.shape}")
print(f"Shape setelah Cleaning : {df.shape}")
print(f"Baris Dihapus : {df_raw.shape[0] - df.shape[0]}")

print()

print("=== Preview Datasets Setelah Cleaning  ==== ")
df[['order_id', 'sales_date', 'product_name', 'category', 'channel', 'quantity', 'price', 'total_sales','rating', 'rating_category', 'status']].head()

=== PERBANDINGAN SEBELUM VS SESUDAH CLEANING ===
Shape Awal : (20007, 16)
Shape setelah Cleaning : (19932, 19)
Baris Dihapus : 75

=== Preview Datasets Setelah Cleaning  ====

,order_id,sales_date,product_name,category,channel,quantity,price,total_sales,rating,rating_category,status
0,P00001,2025-01-01,Minyak Goreng,Makanan,Online - Toko Oren,1,18000.0,37999.15,5,Positif,Returned
1,P00002,2025-01-01,Kopi,Makanan,Offline,3,25000.0,96999.15,4,Positif,Failed
2,P00003,2025-01-01,Deterjen,Pembersih,Offline,3,10000.0,54999.15,1,Negatif,Pending
3,P00004,2025-01-01,Minyak Goreng,Makanan,Online - Toko Oren,1,18000.0,37999.15,3,Netral,Pending
4,P00005,2025-01-01,Pasta Gigi,Perawatan,Online - Toko Oren,3,15000.0,56999.15,1,Negatif,Returned

### Step 5 : Analisis - Jawab Business Questions

In [11]:
# ============================================================
# Q1: Revenue & komposisi per kategori produk?
# ============================================================

rev_per_kategori = df.groupby('category').agg(
    Total_Revenue = ('total_sales', 'sum'),
    Jumlah_Transaksi = ('order_id', 'count'),
    Total_Quantity = ('quantity', 'sum'),
    AVG_Transaksi = ('total_sales', 'mean')
).sort_values(by='Total_Revenue', ascending=False).reset_index()

rev_per_kategori['Share_%'] = (rev_per_kategori['Total_Revenue'] / rev_per_kategori['Total_Revenue'].sum() * 100).round(1)
rev_per_kategori['Revenue_format'] = rev_per_kategori['Total_Revenue'].apply(lambda x: f"Rp {x:,.0f}")

print("=== Q1 : REVENUE PER KATEGORI PRODUK ===")
print(rev_per_kategori[['category','Revenue_format', 'Jumlah_Transaksi', 'Total_Quantity', 'AVG_Transaksi','Share_%']])

=== Q1 : REVENUE PER KATEGORI PRODUK ===
    category  Revenue_format  Jumlah_Transaksi  Total_Quantity  AVG_Transaksi  \
0    Makanan  Rp 335,417,037              6019           12047   55726.372695
1  Perawatan  Rp 288,210,108              5951           11906   48430.533994
2  Pembersih  Rp 254,157,115              7962           15842   31921.265417

   Share_%
0     38.2
1     32.8
2     29.0

In [12]:
# ============================================================
# Q2: Channel penjualan paling menguntungkan?
# ============================================================


rev_per_channel = df.groupby('channel').agg(
    Total_Revenue = ('total_sales', 'sum'),
    Jumlah_Transaksi = ('order_id', 'count'),
    AVG_Rating = ('rating', 'mean')
).sort_values('Total_Revenue', ascending=False).reset_index()

rev_per_channel['Revenue_format'] = rev_per_channel['Total_Revenue'].apply(lambda r: f"Rp {r: ,.0f}")
rev_per_channel['Share_%'] = (rev_per_channel['Total_Revenue'] / rev_per_channel['Total_Revenue'].sum() * 100).round(1)
rev_per_channel['AVG_Rating'] = rev_per_channel['AVG_Rating'].round(2)

print("=== Q2 : REVENUE PER CHANNEL ===")
print(rev_per_channel[['channel', 'Revenue_format', 'Jumlah_Transaksi', 'AVG_Rating', 'Share_%']])

=== Q2 : REVENUE PER CHANNEL ===
               channel   Revenue_format  Jumlah_Transaksi  AVG_Rating  Share_%
0              Offline  Rp  294,760,415              6647        3.01     33.6
1  Online - Toko Hijau  Rp  291,894,407              6657        2.99     33.3
2   Online - Toko Oren  Rp  291,129,438              6628        3.00     33.2

In [13]:
# ============================================================
# Q3: Tren penjualan per bulan?
# ============================================================


rev_per_bulan = df.groupby(['month','month_name']).agg(
    Total_Revenue = ('total_sales', 'sum'),
    Jumlah_Order = ('order_id', 'count')
).reset_index().sort_values('month')

print("=== Q3 : REVENUE PER BULAN ===")
max_rev = rev_per_bulan['Total_Revenue'].max()
for _, row in rev_per_bulan.iterrows():
    bar = '█' * int(row['Total_Revenue'] / max_rev *40)
    print(f"{row['month_name']:10} | {bar: <40} | Rp {row['Total_Revenue']:< 15,.0f} ({row['Jumlah_Order']:,} orders)")

=== Q3 : REVENUE PER BULAN ===
January    | ███████████████████████████████████████  | Rp  75,897,293     (1,721 orders)
February   | ███████████████████████████████████      | Rp  67,710,485     (1,529 orders)
March      | ███████████████████████████████████████  | Rp  76,469,303     (1,714 orders)
April      | ██████████████████████████████████████   | Rp  73,357,351     (1,665 orders)
May        | ██████████████████████████████████████   | Rp  74,663,327     (1,690 orders)
June       | █████████████████████████████████████    | Rp  71,166,384     (1,631 orders)
July       | ████████████████████████████████████████ | Rp  76,848,277     (1,739 orders)
August     | █████████████████████████████████████    | Rp  72,857,355     (1,660 orders)
September  | ████████████████████████████████████     | Rp  70,684,403     (1,612 orders)
October    | █████████████████████████████████████    | Rp  72,653,351     (1,667 orders)
November   | ███████████████████████████████████████  | Rp  75,440,317     (1,701 orders)
December   | ████████████████████████████████████     | Rp  70,036,414     (1,603 orders)

In [14]:
# ============================================================
# Q4: Produk paling laris?
# ============================================================

top_produk = df.groupby('product_name').agg(
    Total_Revenue = ('total_sales', 'sum'),
    Jumlah_Terjual = ('quantity', 'sum'),
    Total_Quantity = ('order_id', 'count'),
    AVG_Rating = ('rating', 'mean')
).sort_values('Total_Revenue', ascending=False).head(10).reset_index()

top_produk['Revenue_format'] = top_produk['Total_Revenue'].apply(lambda r: f"Rp {r:,.0f}")
top_produk['AVG_Rating'] = top_produk['AVG_Rating'].round(2)

print("=== Q4 : TOP 10 PRODUK PALING LARIS BERDASARKAN REVENUE ===")
print()
print(top_produk[['product_name','Revenue_format', 'Jumlah_Terjual', 'Total_Quantity',  'AVG_Rating']].to_string(index=False))

=== Q4 : TOP 10 PRODUK PALING LARIS BERDASARKAN REVENUE ===

    product_name Revenue_format  Jumlah_Terjual  Total_Quantity  AVG_Rating
            Kopi Rp 134,861,983            4026            2037        3.05
          Shampo Rp 110,000,089            3842            1932        2.97
   Minyak Goreng Rp 107,254,017            4065            2001        2.97
      Pasta Gigi  Rp 97,262,960            4108            2061        3.07
             Teh  Rp 93,301,037            3956            1981        3.02
 Pembersih Wajah  Rp 80,947,060            3956            1958        2.97
        Deterjen  Rp 72,648,061            3942            1957        2.98
Pembersih Lantai  Rp 63,840,068            3858            1951        2.97
     Sabun Mandi  Rp 63,761,952            4097            2068        3.01
      Sabun Cuci  Rp 53,907,035            3945            1986        2.99

In [15]:
# ============================================================
# Q5: Kota dengan penjualan tertinggi?
# ============================================================

rev_per_kota = df.groupby('customer_address').agg(
    Total_Revenue = ('total_sales', 'sum'),
    Jumlah_Order = ('order_id', 'count'),
    Avg_of_Order = ('total_sales', 'mean')
).sort_values('Total_Revenue', ascending=False).reset_index()

print("=== Q5 : KOTA DENGAN PENJUALAN TERTINGGI ===")
max_rev = rev_per_kota['Total_Revenue'].max()
for _ , row in rev_per_kota.iterrows():
    bar = '█' * int(row['Total_Revenue'] / max_rev *40)
    print(f"{row['customer_address']:15} | {bar: <40} | Rp {row['Total_Revenue'] : < 15,.0f} ({row['Jumlah_Order']: ,} orders) | Avg Order : Rp {row['Avg_of_Order'] :,.0f}")

print(f"\n 🏆 Kota Teratas: {rev_per_kota.iloc[0]['customer_address']} (Rp {rev_per_kota.iloc[0]['Total_Revenue']:,.0f})")

=== Q5 : KOTA DENGAN PENJUALAN TERTINGGI ===
Samarinda       | ████████████████████████████████████████ | Rp  73,500,718     ( 1,292 orders) | Avg Order : Rp 56,889
Bali            | ███████████████████████████████████████  | Rp  71,810,621     ( 1,391 orders) | Avg Order : Rp 51,625
Medan           | ██████████████████████████████████████   | Rp  70,084,656     ( 1,356 orders) | Avg Order : Rp 51,685
Makassar        | ████████████████████████████████████     | Rp  66,851,651     ( 1,363 orders) | Avg Order : Rp 49,047
Malang          | ██████████████████████████████████       | Rp  63,096,683     ( 1,330 orders) | Avg Order : Rp 47,441
Surabaya        | ██████████████████████████████████       | Rp  62,484,662     ( 1,352 orders) | Avg Order : Rp 46,216
Yogyakarta      | █████████████████████████████████        | Rp  61,638,656     ( 1,358 orders) | Avg Order : Rp 45,389
Palembang       | ████████████████████████████████         | Rp  59,979,682     ( 1,330 orders) | Avg Order : Rp 45,098
Jakarta         | ██████████████████████████████           | Rp  56,416,684     ( 1,329 orders) | Avg Order : Rp 42,450
Semarang        | ██████████████████████████████           | Rp  56,003,679     ( 1,334 orders) | Avg Order : Rp 41,982
Tangerang       | ████████████████████████████             | Rp  51,825,722     ( 1,292 orders) | Avg Order : Rp 40,113
Bogor           | ████████████████████████████             | Rp  51,582,711     ( 1,304 orders) | Avg Order : Rp 39,557
Bekasi          | ██████████████████████████               | Rp  49,244,748     ( 1,265 orders) | Avg Order : Rp 38,929
Depok           | █████████████████████████                | Rp  47,101,711     ( 1,301 orders) | Avg Order : Rp 36,204
Bandung         | ███████████████████                      | Rp  36,161,678     ( 1,335 orders) | Avg Order : Rp 27,087

 🏆 Kota Teratas: Samarinda (Rp 73,500,718)

In [16]:
# ============================================================
# Q6: Distribusi status order & rating pelanggan?
# ============================================================
status_dist = df['status'].value_counts().reset_index()
status_dist.columns = ['Status', 'Jumlah']
status_dist['Persentase'] = (status_dist['Jumlah'] / status_dist['Jumlah'].sum() * 100).round(1)

print('=== Q6A: DISTRIBUSI STATUS ORDER ===')
print(status_dist.to_string(index=False))

print()
rating_dist = df['rating'].value_counts().sort_index()
print('=== Q6B: DISTRIBUSI RATING PELANGGAN ===')
for rating, count in rating_dist.items():
    bintang = '⭐' * int(rating)
    bar     = '█' * int(count / rating_dist.max() * 30)
    print(f'{bintang} {bar:<30} {count:,}')

print(f'\nRata-rata rating: {df["rating"].mean():.2f} / 5')

=== Q6A: DISTRIBUSI STATUS ORDER ===
  Status  Jumlah  Persentase
  Failed    5072        25.4
  Sukses    5030        25.2
Returned    4975        25.0
 Pending    4855        24.4

=== Q6B: DISTRIBUSI RATING PELANGGAN ===
⭐ ██████████████████████████████ 4,043
⭐⭐ █████████████████████████████  3,910
⭐⭐⭐ █████████████████████████████  4,017
⭐⭐⭐⭐ █████████████████████████████  3,942
⭐⭐⭐⭐⭐ █████████████████████████████  4,020

Rata-rata rating: 3.00 / 5

In [17]:
# ============================================================
# Q7 : Siapa Pelanggan Paling Aktif?
# ============================================================

pelanggan_aktif = df.groupby('customer_name').agg(
    Total_Revenue = ('total_sales', 'sum'),
    Jumlah_Order = ('order_id', 'count'),
).sort_values(['Jumlah_Order', 'Total_Revenue'], ascending=[False,False]).head(10).reset_index()

pelanggan_aktif['Total_Revenue_Format'] = pelanggan_aktif['Total_Revenue'].apply(lambda r: f"Rp {r:,.0f}")

print("=== Q7 : PELANGGAN PALING AKTIF ===")
print(pelanggan_aktif[['customer_name', 'Jumlah_Order', 'Total_Revenue_Format']].to_string(index=False))

=== Q7 : PELANGGAN PALING AKTIF ===
customer_name  Jumlah_Order Total_Revenue_Format
          Eka           416        Rp 17,849,588
         Wira           410        Rp 18,349,593
        Yusuf           386        Rp 16,763,618
        Citra           243        Rp 10,834,760
          Oki           241        Rp 10,793,762
         Tina           240        Rp 10,720,762
         Yuni           239        Rp 10,836,763
          Nia           238        Rp 10,360,765
       Stefan           233         Rp 9,853,769
       Shinta           232        Rp 10,331,770

In [18]:
# ============================================================
# Q8 : Kategori Terlaris pada Setiap Channel
# ============================================================

kategori_channel = df.groupby(['channel', 'category']).agg(
    Total_Revenue = ('total_sales', 'sum'),
    Jumlah_Order = ('order_id', 'count'),
    Total_Quantity = ('quantity', 'sum')
).sort_values(['channel', 'Total_Revenue'], ascending=[True,False]).reset_index()

for channel in kategori_channel['channel'].unique():
    print(f"\nChannel : {channel}")

    subset = kategori_channel[kategori_channel['channel'] == channel]

    for _, row in subset.iterrows():
        print(f"{row['category']:<15} | Rp {row['Total_Revenue']:>15,.0f}   ({row['Jumlah_Order']:,} Orders) | Total Qty : {row['Total_Quantity']:,}")

Channel : Offline
Makanan         | Rp     114,942,969   (2,052 Orders) | Total Qty : 4,128
Perawatan       | Rp      96,669,032   (1,986 Orders) | Total Qty : 4,019
Pembersih       | Rp      83,148,414   (2,609 Orders) | Total Qty : 5,193

Channel : Online - Toko Hijau
Makanan         | Rp     109,406,046   (1,970 Orders) | Total Qty : 3,959
Perawatan       | Rp      97,015,013   (2,007 Orders) | Total Qty : 4,011
Pembersih       | Rp      85,473,348   (2,680 Orders) | Total Qty : 5,309

Channel : Online - Toko Oren
Makanan         | Rp     111,068,022   (1,997 Orders) | Total Qty : 3,960
Perawatan       | Rp      94,526,063   (1,958 Orders) | Total Qty : 3,876
Pembersih       | Rp      85,535,353   (2,673 Orders) | Total Qty : 5,340